#应用名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunny1985/Spring-Cloud.git
          search-paths: spring-cloud-start/cloud-repo
          username:
          password:

# 端口
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://ip239:1112/eureka/,http://ip251:1113/eureka/

